#!/usr/bin/env bash
# audit-images.sh — regenerate mobile/assets/images/MANIFEST.md deterministically.
#
# For every PNG under the Flutter app's declared image asset dirs it records
# dimensions, byte size, alpha presence, dominant background colour, distinct
# colour count, a theme-adaptive/brand-locked classification, call sites, and
# notes. Re-running on the same inputs produces byte-identical output, so
# `make verify-image-manifest` can fail when the committed manifest is stale.
#
# Requires ImageMagick 7 (`magick`). Build-time tool only (see CLAUDE.md §2 / §10).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IMG_DIR="$ROOT/mobile/assets/images"
LIB_DIR="$ROOT/mobile/lib"
MANIFEST="$IMG_DIR/MANIFEST.md"

if ! command -v magick >/dev/null 2>&1; then
  echo "audit-images: ImageMagick 'magick' not found — install via 'brew install imagemagick' (build-time tool)." >&2
  exit 2
fi

# Byte size, cross-platform. GNU stat (Linux/CI) first: `-c %s`. BSD stat (macOS
# dev) doesn't support -c → fall back to `-f %z`. The previous order tried BSD
# `-f %z` first, which on Linux means --file-system and emitted filesystem stats
# (Block size/Inodes…) into the manifest's Bytes column → CI manifest diff.
bytes_of() { stat -c '%s' "$1" 2>/dev/null || stat -f '%z' "$1"; }

tmp="$(mktemp)"
{
  echo "# Image asset manifest"
  echo
  echo "_Generated by \`tool/audit-images.sh\`. Do not edit by hand; run the script to regenerate._"
  echo "_Enforced by \`make verify-image-manifest\` (part of \`make verify\`)._"
  echo
  echo "| Path | Dimensions | Bytes | Alpha | Dominant bg | Colors | Classification | Used at | Notes |"
  echo "|---|---|---|---|---|---|---|---|---|"

  # Null-delimited + sorted for determinism; tolerant of spaces/UTF-8 in names.
  find "$IMG_DIR" -type f -name '*.png' -print0 | LC_ALL=C sort -z | while IFS= read -r -d '' f; do
    rel="${f#"$ROOT"/}"
    base="$(basename "$f")"
    dims="$(magick identify -format '%wx%h' "$f[0]")"
    bytes="$(bytes_of "$f")"
    colors="$(magick identify -format '%k' "$f[0]")"

    case "$(magick identify -format '%A' "$f[0]")" in
      True|Blend|Associated) alpha="Yes" ;;
      *) alpha="No" ;;
    esac

    # Dominant background: the top-left corner pixel. These marks sit on a
    # uniform field, so the corner is the background; an exact pixel read is
    # deterministic across ImageMagick versions (histogram quantisation is not).
    bg="$(magick "$f[0]" -format '#%[hex:p{0,0}]' info: 2>/dev/null | tr 'a-f' 'A-F')"

    # Classification: a tintable icon has an alpha channel and very few hues.
    # Everything else (multi-colour, opaque surface) is brand-locked.
    if [ "$alpha" = "Yes" ] && [ "$colors" -le 4 ]; then
      cls="theme-adaptive"
    else
      cls="brand-locked"
    fi

    used="$(cd "$ROOT" && grep -rlF --include='*.dart' "$base" "$LIB_DIR" 2>/dev/null \
            | sed "s#$ROOT/##" | LC_ALL=C sort | paste -sd '; ' -)"
    [ -z "$used" ] && used="(none)"

    notes=""
    case "$used" in
      *mopro_logo.dart*) notes="MoproLogo dual-asset (light=beyaz/white, dark=siyah/black). Leave as-is per §2.3 — multi-colour brand mark, variant-selected." ;;
    esac

    echo "| \`$rel\` | $dims | $bytes | $alpha | $bg | $colors | $cls | $used | $notes |"
  done
} >"$tmp"

mv "$tmp" "$MANIFEST"
echo "audit-images: wrote $MANIFEST"
