#!/usr/bin/env bash
# tool/audit/regen.sh
#
# PURPOSE
#   Run every audit inventory script and splice its Markdown output into the
#   matching autogenerated block of SYSTEM_AUDIT.md. Each block is delimited by
#       <!-- BEGIN:gen:NAME -->  ...  <!-- END:gen:NAME -->
#   and only the content between the markers is replaced; handwritten prose is
#   untouched. Because every script is deterministic, re-running produces no
#   diff (verified by `make audit` + `git diff --exit-code`).
#
# USAGE
#   tool/audit/regen.sh            # rewrite generated blocks in SYSTEM_AUDIT.md
#   tool/audit/regen.sh --check    # fail if regenerating would change the file
#   tool/audit/regen.sh --help
#
# EXTEND
#   Add a "NAME|command" line to $JOBS and a matching marker pair in the doc.
set -euo pipefail

case "${1:-}" in
  -h|--help)
    sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
esac

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
DOC="SYSTEM_AUDIT.md"
A="tool/audit"

# NAME|command  — NAME must match a <!-- BEGIN:gen:NAME --> block in the doc.
JOBS=(
  "endpoints|bash $A/list_endpoints.sh"
  "routes|dart run $A/list_routes.dart"
  "providers|dart run $A/list_providers.dart"
  "schema|bash $A/dump_schema.sh"
  "i18n|bash $A/check_i18n.sh"
)

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1
TARGET="$DOC"
if [ "$CHECK" -eq 1 ]; then
  TARGET="$(mktemp)"
  cp "$DOC" "$TARGET"
fi

splice() { # $1=name $2=content-file $3=doc
  awk -v name="$1" -v cf="$2" '
    $0 ~ ("<!-- BEGIN:gen:" name " -->") {
      print
      while ((getline line < cf) > 0) print line
      close(cf)
      skip = 1
      next
    }
    $0 ~ ("<!-- END:gen:" name " -->") { skip = 0; print; next }
    !skip { print }
  ' "$3" > "$3.tmp" && mv "$3.tmp" "$3"
}

for job in "${JOBS[@]}"; do
  name="${job%%|*}"; cmd="${job#*|}"
  if ! grep -q "<!-- BEGIN:gen:$name -->" "$TARGET"; then
    echo "regen: WARNING — no marker block for '$name' in $DOC" >&2
    continue
  fi
  tmp="$(mktemp)"
  # shellcheck disable=SC2086
  $cmd > "$tmp"
  splice "$name" "$tmp" "$TARGET"
  rm -f "$tmp"
done

if [ "$CHECK" -eq 1 ]; then
  if diff -q "$DOC" "$TARGET" >/dev/null; then
    echo "regen --check: $DOC is up to date."
    rm -f "$TARGET"
  else
    echo "regen --check: $DOC is STALE — run 'make audit'." >&2
    diff "$DOC" "$TARGET" || true
    rm -f "$TARGET"
    exit 1
  fi
else
  echo "regen: rewrote generated blocks in $DOC."
fi
